@startuml

class Main{
public static void main(String[] args)
}

class GamePanel{
- int FPS
- int windowLength
- int windowHeight
+ createWindow()
+ run()
+ update()
+ draw()
}

class KeyHandler{
+ boolean UP
+ boolean DOWN
+ boolean LEFT
+ boolean RIGHT
+ boolean Interact
+ void KeyPressed()
+ void KeyReleased()
}




class Tiles{
- String name
- int id
- int XPos
- int YPos
}

class Terrain extends Tiles{
- boolean isWalkable
+ void collision()
}

class Entity{
- String name
- int id
- int XPos
- int YPos
- int movementSpeed
}

class GUI{
- String previousMessage
+ void displayMessage()
+ void previousMessage()
+ void messageDivider()
+ String getMessage(Entity E, String event)
}

class Location{
- int XPos
- int YPos
- int LocationWidth
- int LocationHeight
+ void drawLocation()
+ void getLocation()
}

class Player extends Entity implements KeyHandler{

}

class NPC extends Entity{
+ boolean hasMainEvent
+ boolean hasSideEvent
+ String NpcMessage
+ void interact()
+ void unlockMainEvent()
+ void unlockSideEvent()
}

class MainEvent {
- {static} int eventNumber
+ int getEventNumber()
+ void setEventNumber()
}

class SideEvent{
- boolean unlocked
- int sideEventNumber
}

class SoundSystem{
- collection<mp3File>
+ mp3File loadMp3()
+ void playMusic(mp3File music)
+ void playSound(mp3File sound)
}

class Resources{
- sprite imageID
- collection<sprite> animation
+ sprite getSprite()
+ void drawSprite(sprite sprite, int xPos, int yPos)
+ void drawSprite(collection<sprite> animation, int xPos, int yPos)
+ void getImage()
+ void setImage()
+ void getAnimation()
+ void setAnimation()
}

class FileIO{
+ void loadFile()
+ void loadSprite()
+ void loadMp3()
+ void readFile()
+ void readSprite()
+ void readMp3()
}



Main -- GamePanel

GamePanel -- Resources
GamePanel -- KeyHandler

Resources -- Tiles
Resources -- Entity
Resources -- GUI

Tiles -- Location

Entity -- GUI

SoundSystem .. Entity
SoundSystem .. Location
SoundSystem .. KeyHandler

MainEvent -- Location
MainEvent -- NPC
SideEvent -- NPC

@enduml